pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                echo "Inside Deliver Stage. Comment out the below -new pipeline branch"
               /* sh './jenkins/scripts/deliver.sh' */
            }
        }
        stage('Complete') {
            steps {
                echo "Job Completed Successfully - new pipeline branch"
            }
        }
    }
}
