pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                cd 'C:\ProgramData\Jenkins\.jenkins\workspace\My-Simple-Java-Maven-App\jenkins\scripts'
                sh 'deliver.sh'
            }
        }
    }
}
